# Spring Application Name

spring.application.name=chatapp

# Jackson Configuration for Date Serialization
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# JWT Configuration
jwt.secret=verysecretkey-for-dev-change-this-to-a-secure-random-value
jwt.expirationMs=86400000

# Spring Profile


## DataSource Configuration (Oracle)
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freeXDB
#spring.datasource.username=system
#spring.datasource.password=RIZWAN11
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
## JPA / Hibernate Configuration
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update
# Set to 'none' in production when schema managed separately
spring.jpa.show-sql=true
# Server Port Configuration (ignored when deployed to external Tomcat)
server.port=8080

# Context path is determined by WAR file name when deployed to Tomcat
# For standalone: server.servlet.context-path=/chatapp


# ==========================================
# LOGGING CONFIGURATION
# ==========================================

# Log file name (will be created automatically)
logging.file.name=logs/chatapp.log

# Log level for your entire application
logging.level.root=INFO

logging.level.com.aksa.chatapp=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
